### ISSUE TITLE
TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by Ginden** [darky/bull-repl#7]
```
BULL-REPL | bull.....> active

TypeError: Cannot read property 'id' of null
    at jobs.map.job (/home/futuremind_admin/.npm/_npx/10019/lib/node_modules/bull-repl/src/utils.js:22:17)
    at Array.map (<anonymous>)
    at Object.exports.showJobs (/home/futuremind_admin/.npm/_npx/10019/lib/node_modules/bull-repl/src/utils.js:21:23)
    at CommandInstance.exports.vorpal.command.option.option.action (/home/futuremind_admin/.npm/_npx/10019/lib/node_modules/bull-repl/index.js:38:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by darky** [comment]
Thanks for issue, @Ginden 
Quick fix in `0.16.1` version
Can you please provide more info about how it receive `null` instead of active job?

**Comment by Ginden** [comment]
> Can you please provide more info about how it receive null instead of active job?

That's good question, I have no idea. Probably bug in Bull's code.

**Comment by darky** [comment]
Hmm, ok. I close this issue.
Please, write here, if you get news about this problem.
